[project]
name = "plyaska-lib"
version = "0.1.0"
description = "Plyasky is a backend library for fast development."
readme = "README.md"
authors = [
    { name = "VitaPasser", email = "vitapasser@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beanie>=2.0.0",
    "fastapi[all,standard]>=0.116.2",
    "httpsx>=0.0.1",
    "inflect>=7.5.0",
    "inflection>=0.5.1",
    "mkinit>=1.1.0",
    "pydantic-settings>=2.10.1",
    "pydantic[email]>=2.11.9",
    "pymongo>=4.15.1",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.1",
    "redis[hiredis]>=7.0.0",
    "setuptools>=80.9.0",
    "uv-build>=0.8.20,<0.9.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "asgi-lifespan>=2.1.0",
    "coverage>=7.10.7",
    "debugpy>=1.8.17",
    "typer>=0.17.4",
    "rust-just>=1.42.4",
    "faker>=37.12.0",
    "locust>=2.42.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
